language: python
python:
  - "3.7"
installï¼š
  - pip freeze > requirements.txt
  
# command to run tests
script:
  - python -m  unittest discover -s  Tests

branches:
  only:
    - master
    - development
